[pytest]
encoding = utf-8

log_cli = true
log_cli_level = INFO

addopts = -ra -q --tb=short

testpaths = 
    tests

markers =
    faq: Тесты раздела FAQ
    order: Тесты оформления заказа